// <auto-generated />
namespace MediInfo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class applicationc9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(applicationc9));
        
        string IMigrationMetadata.Id
        {
            get { return "202011090255124_application-c9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
